name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0 # Use the appropriate Ruby version

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build and deploy
        run: |
          # Add your build and deploy commands here, such as Jekyll build or Hugo build

